CoreWebApp/Controllers/EmployeeController.cs
using CoreWebApp.Models;
using CoreWebApp.Models.ViewModels;
using CoreWebApp.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CoreWebApp.Controllers
{
    public class EmployeeController : Controller
    {
        private IEmployeeRepository _employeeRepository;
        private IWebHostEnvironment _environment;

        public EmployeeController(IEmployeeRepository employeeRepository, IWebHostEnvironment environment)
        {
            _employeeRepository = employeeRepository;
            _environment = environment;
        }
        [Authorize(Roles = "Admin , User")]
        public IActionResult Index()
        {
            IEnumerable<Employee> list=_employeeRepository.GetAllEmployees().ToList();
            ViewBag.Title = "Employee List";
            return View(list);
        }

        [Authorize(Roles = "Shefain")]
        public IActionResult Details(int id)
        {
            Employee model= _employeeRepository.GetEmployeeById(id);
            string name= model.Name;
            ViewBag.Title = "Employee Details";
            return View(model);
        }
        public IActionResult Create()
        {
            ViewBag.Title = "Employee Create";
            return View();
        }
        [HttpPost]
        public IActionResult Create(EmployeeCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName =ProcessUploadFile(model);
              
                Employee newEmployee = new Employee
                {
                    Name = model.Name,
                    Email = model.Email,
                    Department = model.Department,
                    PhotoPath = uniqueFileName
                };
                _employeeRepository.Save(newEmployee);
                return RedirectToAction("Details", new { id = newEmployee.Id });

            }
            return View();
        }

        public IActionResult Edit(int id)
        {
            Employee employee=_employeeRepository.GetEmployeeById(id);
            EmployeeEditViewModel model = new EmployeeEditViewModel
            {
                Id = employee.Id,
                Name = employee.Name,
                Email = employee.Email,
                Department = employee.Department,
                ExistingPhotopath = employee.PhotoPath
            };
            return View(model);
        }
        [HttpPost]
        public IActionResult Edit(EmployeeEditViewModel model)
        {
            //if (ModelState.IsValid)
            {
                Employee employee = _employeeRepository.GetEmployeeById(model.Id);
                employee.Name= model.Name;
                employee.Email= model.Email;
                employee.Department= model.Department;
                if (model.Photo!=null)
                {
                    if (!string.IsNullOrEmpty(model.ExistingPhotopath))
                    {
                        string filePath1=Path.Combine(_environment.WebRootPath,"images",model.ExistingPhotopath);
                        System.IO.File.Delete(filePath1);
                    }

                    employee.PhotoPath = ProcessUploadFile(model);


                }
                Employee upEmployee = _employeeRepository.Update(employee);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public IActionResult Delete(int id)
        {
            Employee employee = _employeeRepository.GetEmployeeById(id);
            if (employee != null)
            {
                _employeeRepository.Delete(employee.Id);
                return RedirectToAction("Index");
            }
            
            return View();
        }

        private string ProcessUploadFile(EmployeeCreateViewModel model)
        {
            string uniqueFileName = "";
            if (model.Photo!=null)
            {
                string uploadFolder = Path.Combine(_environment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;
                string filePath = Path.Combine(uploadFolder, uniqueFileName);
                using (var fileStream=new FileStream(filePath, FileMode.Create))
                {
                    model.Photo.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }
    }
}

CoreWebApp/Controllers/RoleController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using CoreWebApp.Models.ViewModels;

namespace CoreWebApp.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            var roles = _roleManager.Roles.ToList();
            return View(roles);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(string roleName)
        {
            if (!string.IsNullOrEmpty(roleName))
            {
                if (!await _roleManager.RoleExistsAsync(roleName))
                {
                    await _roleManager.CreateAsync(new IdentityRole(roleName));
                }
            }

            return RedirectToAction("Index");
        }
    }
}

CoreWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Employee Management</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">

                    <li class="nav-item"><a class="nav-link active" aria-current="page" asp-controller="Account" asp-action="AssignRole">AssignRole</a></li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page" asp-controller="Account" asp-action="UsersWithRoles">UserWith</a></li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page" asp-controller="Role" asp-action="Index">RoleList</a></li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page" asp-controller="Role" asp-action="Create">CrearteRoleList</a></li>

                    @if (signInManager.IsSignedIn(User))
                    {
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="Employee" asp-action="Index">Employee List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Employee" asp-action="Create">Create Employee</a>
                        </li>
                        <li class="nav-item">
                            <form method="post" asp-controller="Account" asp-action="Logout" class="nav-link">
                                <button type="submit" class="btn btn-link">Logout @User.Identity.Name</button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Registration">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>

    <div class="container mt-4">
        @RenderBody()
    </div>

    <script src="~/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>
</html>